site_name: AppRegistration
site_description: How to Disable OR Enable App registration using pipeline
plugins:
  - techdocs-core
docs_dir: docs
nav:
  - Home: "index.md"
  - "How to Disable OR Enable App registration using pipeline": "How to Disable OR Enable App registration using pipeline.md"
  - "Annual Secure Code Compliance Training": "annual-secure-code-compliance-training.md"
  - "How to Disable OR Enable App registration using pipeline": "How to Disable OR Enable App registration using pipeline.md"


